name: use linux
'on':
  - push
  - pull_request
jobs:
 build: 
  runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Framework SDK
      uses: microsoft/setup-msbuild@v1
     # with:
     #  dotnet-version: 4.7.2
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build
      run: |
        msbuild B1Test.sln /p:Configuration=Release
        
    - name: version
      run: dotnet --info
        
    - name: publish
      run: dotnet publish -r win10-x64 --configuration "Release" --self-contained "true" -o ../publish
      
    - name: Create artifact
      working-directory: B1Test
      run: |
        cd publish
        package=$(echo "$GITHUB_REF_NAME" | awk -F[/] '{print $1}')-$(echo "$GITHUB_REF_NAME" | awk -F[/] '{print $2}')
        zip ../$package-$GITHUB_RUN_NUMBER.zip *

#     - name: upload artifact
#     - uses: actions/upload-artifact@v3
#       with:
#         name: artifact
#         path: |
#           <path to zip file>/src/*.zip
      
#     - name: Generate Artifacts
#       uses: actions/upload-artifact@v3.1.2
#       with:
#         name: Artifacts
#         path: B1Test/bin/*
