
name: Build and Test ASP.NET Web Application
'on':
  - push
  - pull_request

jobs:
 build: 
  permissions: write-all
  runs-on: windows-2019
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework SDK
      uses: microsoft/setup-msbuild@v1
     # with:
     #  dotnet-version: 4.7.2
     
    - name: Restore NuGet packages
      run: nuget restore
      
    #- name: Build
    #  run: msbuild /t:Build /p:Configuration=Release (working)
    #  run: 'msbuild B1Test/B1Test.csproj /p:Configuration=Release'
    
    - name: Build and Publish the project
      run: msbuild B1Test/B1Test.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=MSDeploy /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="/Publish/"

    - name: Generate Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: b1test-Artifacts
        path: |
          /publish
          
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: b1test-Artifacts

